def assert_fight(self, fight, expected):
    self.assertEqual(fight["event"], expected["event"])
    self.assertEqual(fight["fight_id"], expected["fight_id"])
    self.assertEqual(fight["fight_link"], expected["fight_link"])
    self.assertEqual(fight["fighter1"], expected["fighter1"])
    self.assertEqual(fight["fighter2"], expected["fighter2"])
    self.assertEqual(fight["weight_class"], expected["weight_class"])
    self.assertEqual(fight["method"], expected["method"])
    self.assertEqual(fight["round"], expected["round"])
    self.assertEqual(fight["time"], expected["time"])
    self.assertEqual(fight["belt"], expected["belt"])
    self.assertEqual(fight["bonus"], expected["bonus"])
    self.assertEqual(fight["wl_fighter1"], expected["wl_fighter1"])
    self.assertEqual(fight["wl_fighter2"], expected["wl_fighter2"])
